<?xml version="1.0" encoding="UTF-8"?>
<!-- @generated mapFile="ObtenerComentarioSolicitud/input_map_req_1.map" md5sum="5a2d9b33b9df361069ac3b182362395c" version="8.0.400" -->
<!--
*****************************************************************************
*   This file has been generated by the IBM XML Mapping Editor.
*
*   Mapping file:		input_map_req_1.map
*   Map declaration(s):	input_map_req_1
*   Input file(s):		smo://smo/name%3Dwsdl-primary/message%3D%257Bhttp%253A%252F%252FIBCRAAI%252FAIS%252FAIS_ObtenerComentarioSolicitud%257DinvokeMsg/xpath%3D%252Fbody/smo.xsd
*   Output file(s):		smo://smo/name%3Dwsdl-primary/message%3D%257Bhttp%253A%252F%252FIBCRA_Mediaciones_Lib%252FObtenerActividadDesc%252FObtenerActividadDesc%257DObtenerComentarioSolicitudRequestMsg/xpath%3D%252Fbody/smo.xsd
*
*   Note: Do not modify the contents of this file as it is overwritten
*         each time the mapping model is updated.
*****************************************************************************
-->
<xsl:stylesheet
    xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
    xmlns:xalan="http://xml.apache.org/xslt"
    xmlns:math="http://exslt.org/math"
    xmlns:str="http://exslt.org/strings"
    xmlns:set="http://exslt.org/sets"
    xmlns:date="http://exslt.org/dates-and-times"
    xmlns:exsl="http://exslt.org/common"
    xmlns:xs4xs="http://www.w3.org/2001/XMLSchema"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:in2="wsdl.http://IBCRAAI/AIS/AIS_ObtenerComentarioSolicitud"
    xmlns:in3="http://IBCRAAI/AIS/AIS_ObtenerComentarioSolicitud"
    xmlns:io5="http://www.w3.org/2005/08/addressing"
    xmlns:io4="http://www.ibm.com/xmlns/prod/websphere/http/sca/6.1.0"
    xmlns:io3="http://www.ibm.com/websphere/sibx/smo/v6.0.1"
    xmlns:io2="http://www.ibm.com/xmlns/prod/websphere/mq/sca/6.0.0"
    xmlns:io6="http://www.w3.org/2003/05/soap-envelope"
    xmlns:in="http://IBCRABO"
    xmlns:io="http://schemas.xmlsoap.org/ws/2004/08/addressing"
    xmlns:out7="http://IBCRA_Mediaciones_Lib/ObtenerHistoricoInformativa"
    xmlns:out6="http://IBCRA_Mediaciones_Lib/ObtenerActividadDesc"
    xmlns:out3="http://IBCRA_Mediaciones_Lib/ObtenerInformativas"
    xmlns:out2="http://IBCRA_Mediaciones_Lib/ObtenerComentarioSolicitud"
    xmlns:out5="wsdl.http://IBCRA_Mediaciones_Lib/ObtenerActividadDesc/ObtenerActividadDesc"
    xmlns:out4="http://IBCRA_Mediaciones_Lib/ObtenerDatosPortal"
    xmlns:out="http://IBCRA_Mediaciones_Lib/ObtenerActividadDesc/ObtenerActividadDesc"
    xmlns:out9="http://IBCRA_Mediaciones_Lib/ObtenerFechaPorDiaHabilSemestre"
    xmlns:out8="http://IBCRA_Mediaciones_Lib/ObtenerInformativasPlanificadas"
    xmlns:out11="http://IBCRA_Mediaciones_Lib/ObtenerRolesDeInformativa"
    xmlns:out12="http://IBCRA_Mediaciones_Lib/ObtenerMaximoDiaHabilTrimestre"
    xmlns:out28="http://IBCRA_Mediaciones_Lib/ObtenerInformativasReintento"
    xmlns:out10="http://IBCRA_Mediaciones_Lib/ObtenerRolesDeActividad"
    xmlns:out29="http://IBCRA_Mediaciones_Lib/ObtenerFechaPorDiaHabilAnual"
    xmlns:out26="http://IBCRA_Mediaciones_Lib/ObtenerActividadesInformativa"
    xmlns:out27="http://IBCRA_Mediaciones_Lib/ObtenerInformativaRectificativa"
    xmlns:out24="http://IBCRA_Mediaciones_Lib/ObtenerComboInformativas"
    xmlns:out25="http://IBCRA_Mediaciones_Lib/ConsultaInformativaGruposBPM"
    xmlns:out23="http://IBCRA_Mediaciones_Lib/ObtenerFechaPorDiaHabilSemanalC"
    xmlns:out19="http://IBCRA_Mediaciones_Lib/ObtenerPeriodoFecha"
    xmlns:out22="http://IBCRA_Mediaciones_Lib/ObtenerMaximoDiaHabilSemanalC"
    xmlns:out18="http://IBCRA_Mediaciones_Lib/ObtenerTeamInformativa"
    xmlns:out21="http://IBCRA_Mediaciones_Lib/ConsultaInformativaPorID"
    xmlns:out17="http://IBCRA_Mediaciones_Lib/ObtenerFechaPorDiaHabilMes"
    xmlns:out20="http://IBCRA_Mediaciones_Lib/ObtenerMaximoDiaHabilAnual"
    xmlns:out16="http://IBCRA_Mediaciones_Lib/ObtenerInformativasPlanificadasPorFecha"
    xmlns:out15="http://IBCRA_Mediaciones_Lib/ObtenerMaximoDiaHabilSemestre"
    xmlns:out14="http://IBCRA_Mediaciones_Lib/ObtenerInformativaDemanda"
    xmlns:out13="http://IBCRA_Mediaciones_Lib/ObtenerSolicitudInformativa"
    xmlns:out35="http://IBCRA_Mediaciones_Lib/ConsultaInformativaRectificativas"
    xmlns:out36="http://IBCRA_Mediaciones_Lib/IniciarIntanciaInformativa_InsertarSolicitud"
    xmlns:out32="http://IBCRA_Mediaciones_Lib/ConsultaInformativaPorFechas"
    xmlns:out31="http://IBCRA_Mediaciones_Lib/ObtenerFechaPorDiaHabilTrimestre"
    xmlns:out34="http://IBCRA_Mediaciones_Lib/ObtenerSolicitudinformativaActividad"
    xmlns:out33="http://IBCRA_Mediaciones_Lib/ObtenerSolicitudEstadoIdCUP"
    xmlns:out30="http://IBCRA_Mediaciones_Lib/ObtenerMaximoDiaHabilMes"
    xmlns:map="http://IBCRA_AIS/ObtenerComentarioSolicitud/input_map_req_1"
    xmlns:msl="http://www.ibm.com/xmlmap"
    exclude-result-prefixes="math str set date exsl map xalan msl"
    version="1.0">
  <xsl:output method="xml" encoding="UTF-8" indent="no"/>

  <!-- root wrapper template  -->
  <xsl:template match="/">
    <xsl:choose>
      <xsl:when test="msl:datamap">
        <msl:datamap>
          <xsl:element name="dataObject">
            <xsl:attribute name="xsi:type">
              <xsl:value-of select="'out5:ObtenerComentarioSolicitudRequestMsg'"/>
            </xsl:attribute>
            <xsl:call-template name="map:input_map_req_12">
              <xsl:with-param name="body" select="msl:datamap/dataObject[1]"/>
            </xsl:call-template>
          </xsl:element>
        </msl:datamap>
      </xsl:when>
      <xsl:otherwise>
        <xsl:apply-templates select="body" mode="map:input_map_req_1"/>
      </xsl:otherwise>
    </xsl:choose>
  </xsl:template>

  <!-- This rule represents an element mapping: "body" to "body".  -->
  <xsl:template match="body"  mode="map:input_map_req_1">
    <body>
      <xsl:attribute name="xsi:type">
        <xsl:value-of select="'out5:ObtenerComentarioSolicitudRequestMsg'"/>
      </xsl:attribute>
      <out:ObtenerComentarioSolicitud>
        <input_ObtenerComentarioSolicitud>
          <!-- a simple data mapping: "in3:invoke/Solicitud_Id"(string) to "Solicitud_Id"(string) -->
          <xsl:if test="in3:invoke/Solicitud_Id">
            <xsl:element name="Solicitud_Id">
              <xsl:value-of select="in3:invoke/Solicitud_Id"/>
            </xsl:element>
          </xsl:if>
        </input_ObtenerComentarioSolicitud>
      </out:ObtenerComentarioSolicitud>
    </body>
  </xsl:template>

  <!-- This rule represents a type mapping: "body" to "body".  -->
  <xsl:template name="map:input_map_req_12">
    <xsl:param name="body"/>
    <out:ObtenerComentarioSolicitud>
      <input_ObtenerComentarioSolicitud>
        <!-- a simple data mapping: "$body/in3:invoke/Solicitud_Id"(string) to "Solicitud_Id"(string) -->
        <xsl:if test="$body/in3:invoke/Solicitud_Id">
          <xsl:element name="Solicitud_Id">
            <xsl:value-of select="$body/in3:invoke/Solicitud_Id"/>
          </xsl:element>
        </xsl:if>
      </input_ObtenerComentarioSolicitud>
    </out:ObtenerComentarioSolicitud>
  </xsl:template>

  <!-- *****************    Utility Templates    ******************  -->
  <!-- copy the namespace declarations from the source to the target -->
  <xsl:template name="copyNamespaceDeclarations">
    <xsl:param name="root"/>
    <xsl:for-each select="$root/namespace::*[not(name() = '')]">
      <xsl:copy/>
    </xsl:for-each>
  </xsl:template>
</xsl:stylesheet>
