<?xml version="1.0" encoding="UTF-8"?>
<!-- @generated mapFile="ObtenerRolesDeActividad/input_map_RolesActividad.map" md5sum="ed9bc4608a2d6ad4cd9c54b72a56252e" version="8.0.400" -->
<!--
*****************************************************************************
*   This file has been generated by the IBM XML Mapping Editor.
*
*   Mapping file:		input_map_RolesActividad.map
*   Map declaration(s):	input_map_RolesActividad
*   Input file(s):		smo://smo/name%3Dwsdl-primary/message%3D%257Bhttp%253A%252F%252FIBCRAAI%252FAIS%252FAIS_ObtenerRolesDeActividad%257DinvokeMsg/xpath%3D%252Fbody/smo.xsd
*   Output file(s):		smo://smo/name%3Dwsdl-primary/message%3D%257Bhttp%253A%252F%252FIBCRA_Mediaciones_Lib%252FObtenerActividadDesc%252FObtenerActividadDesc%257DObtenerRolesDeActividadRequestMsg/xpath%3D%252Fbody/smo.xsd
*
*   Note: Do not modify the contents of this file as it is overwritten
*         each time the mapping model is updated.
*****************************************************************************
-->
<xsl:stylesheet
    xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
    xmlns:xalan="http://xml.apache.org/xslt"
    xmlns:math="http://exslt.org/math"
    xmlns:str="http://exslt.org/strings"
    xmlns:set="http://exslt.org/sets"
    xmlns:date="http://exslt.org/dates-and-times"
    xmlns:exsl="http://exslt.org/common"
    xmlns:xs4xs="http://www.w3.org/2001/XMLSchema"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:in2="http://IBCRAAI/AIS/AIS_ObtenerRolesDeActividad"
    xmlns:in3="http://IBCRABO"
    xmlns:io5="http://www.ibm.com/xmlns/prod/websphere/http/sca/6.1.0"
    xmlns:io4="http://www.ibm.com/websphere/sibx/smo/v6.0.1"
    xmlns:io3="http://www.ibm.com/xmlns/prod/websphere/mq/sca/6.0.0"
    xmlns:io2="http://www.w3.org/2005/08/addressing"
    xmlns:io6="http://www.w3.org/2003/05/soap-envelope"
    xmlns:in="wsdl.http://IBCRAAI/AIS/AIS_ObtenerRolesDeActividad"
    xmlns:io="http://schemas.xmlsoap.org/ws/2004/08/addressing"
    xmlns:out7="http://IBCRA_Mediaciones_Lib/ObtenerRolesDeInformativa"
    xmlns:out6="http://IBCRA_Mediaciones_Lib/ObtenerInformativas"
    xmlns:out9="http://IBCRA_Mediaciones_Lib/ObtenerSolicitudInformativa"
    xmlns:out8="http://IBCRA_Mediaciones_Lib/ObtenerMaximoDiaHabilTrimestre"
    xmlns:out11="http://IBCRA_Mediaciones_Lib/ObtenerMaximoDiaHabilSemestre"
    xmlns:out3="http://IBCRA_Mediaciones_Lib/ObtenerComentarioSolicitud"
    xmlns:out2="http://IBCRA_Mediaciones_Lib/ObtenerInformativasPlanificadas"
    xmlns:out12="http://IBCRA_Mediaciones_Lib/ObtenerInformativasPlanificadasPorFecha"
    xmlns:out28="http://IBCRA_Mediaciones_Lib/ObtenerFechaPorDiaHabilAnual"
    xmlns:out5="http://IBCRA_Mediaciones_Lib/ObtenerFechaPorDiaHabilSemestre"
    xmlns:out29="http://IBCRA_Mediaciones_Lib/ObtenerMaximoDiaHabilMes"
    xmlns:out10="http://IBCRA_Mediaciones_Lib/ObtenerInformativaDemanda"
    xmlns:out4="http://IBCRA_Mediaciones_Lib/ObtenerRolesDeActividad"
    xmlns:out26="http://IBCRA_Mediaciones_Lib/ObtenerInformativaRectificativa"
    xmlns:out27="http://IBCRA_Mediaciones_Lib/ObtenerInformativasReintento"
    xmlns:out24="http://IBCRA_Mediaciones_Lib/ConsultaInformativaGruposBPM"
    xmlns:out25="http://IBCRA_Mediaciones_Lib/ObtenerActividadesInformativa"
    xmlns:out23="http://IBCRA_Mediaciones_Lib/ObtenerComboInformativas"
    xmlns:out19="http://IBCRA_Mediaciones_Lib/ObtenerActividadDesc"
    xmlns:out22="http://IBCRA_Mediaciones_Lib/ObtenerFechaPorDiaHabilSemanalC"
    xmlns:out18="wsdl.http://IBCRA_Mediaciones_Lib/ObtenerActividadDesc/ObtenerActividadDesc"
    xmlns:out21="http://IBCRA_Mediaciones_Lib/ObtenerMaximoDiaHabilSemanalC"
    xmlns:out17="http://IBCRA_Mediaciones_Lib/ObtenerMaximoDiaHabilAnual"
    xmlns:out20="http://IBCRA_Mediaciones_Lib/ConsultaInformativaPorID"
    xmlns:out16="http://IBCRA_Mediaciones_Lib/ObtenerPeriodoFecha"
    xmlns:out15="http://IBCRA_Mediaciones_Lib/ObtenerDatosPortal"
    xmlns:out14="http://IBCRA_Mediaciones_Lib/ObtenerTeamInformativa"
    xmlns:out13="http://IBCRA_Mediaciones_Lib/ObtenerFechaPorDiaHabilMes"
    xmlns:out35="http://IBCRA_Mediaciones_Lib/ObtenerHistoricoInformativa"
    xmlns:out32="http://IBCRA_Mediaciones_Lib/ObtenerSolicitudEstadoIdCUP"
    xmlns:out31="http://IBCRA_Mediaciones_Lib/ConsultaInformativaPorFechas"
    xmlns:out34="http://IBCRA_Mediaciones_Lib/IniciarIntanciaInformativa_InsertarSolicitud"
    xmlns:out33="http://IBCRA_Mediaciones_Lib/ConsultaInformativaRectificativas"
    xmlns:out30="http://IBCRA_Mediaciones_Lib/ObtenerFechaPorDiaHabilTrimestre"
    xmlns:out="http://IBCRA_Mediaciones_Lib/ObtenerActividadDesc/ObtenerActividadDesc"
    xmlns:out36="http://IBCRA_Mediaciones_Lib/ObtenerSolicitudinformativaActividad"
    xmlns:map="http://IBCRA_AIS/ObtenerRolesDeActividad/input_map_RolesActividad"
    xmlns:msl="http://www.ibm.com/xmlmap"
    exclude-result-prefixes="math str set date exsl map xalan msl"
    version="1.0">
  <xsl:output method="xml" encoding="UTF-8" indent="no"/>

  <!-- root wrapper template  -->
  <xsl:template match="/">
    <xsl:choose>
      <xsl:when test="msl:datamap">
        <msl:datamap>
          <xsl:element name="dataObject">
            <xsl:attribute name="xsi:type">
              <xsl:value-of select="'out18:ObtenerRolesDeActividadRequestMsg'"/>
            </xsl:attribute>
            <xsl:call-template name="map:input_map_RolesActividad2">
              <xsl:with-param name="body" select="msl:datamap/dataObject[1]"/>
            </xsl:call-template>
          </xsl:element>
        </msl:datamap>
      </xsl:when>
      <xsl:otherwise>
        <xsl:apply-templates select="body" mode="map:input_map_RolesActividad"/>
      </xsl:otherwise>
    </xsl:choose>
  </xsl:template>

  <!-- This rule represents an element mapping: "body" to "body".  -->
  <xsl:template match="body"  mode="map:input_map_RolesActividad">
    <body>
      <xsl:attribute name="xsi:type">
        <xsl:value-of select="'out18:ObtenerRolesDeActividadRequestMsg'"/>
      </xsl:attribute>
      <out:ObtenerRolesDeActividad>
        <input_ObtenerRolesDeActividad>
          <!-- a simple data mapping: "in2:invoke/idInformativa"(int) to "ObtenerRolesDeActividad"(int) -->
          <xsl:if test="in2:invoke/idInformativa">
            <xsl:element name="ObtenerRolesDeActividad">
              <xsl:value-of select="in2:invoke/idInformativa"/>
            </xsl:element>
          </xsl:if>
          <!-- a simple data mapping: "in3:Item"(int) to "EtapaId"(int) -->
          <xsl:for-each select="in2:invoke/idEtapa/in3:Item">
            <!-- a simple data mapping: "."(int) to "EtapaId"(int) -->
            <xsl:if test=".">
              <EtapaId>
                <xsl:value-of select="."/>
              </EtapaId>
            </xsl:if>
          </xsl:for-each>
        </input_ObtenerRolesDeActividad>
      </out:ObtenerRolesDeActividad>
    </body>
  </xsl:template>

  <!-- This rule represents a type mapping: "body" to "body".  -->
  <xsl:template name="map:input_map_RolesActividad2">
    <xsl:param name="body"/>
    <out:ObtenerRolesDeActividad>
      <input_ObtenerRolesDeActividad>
        <!-- a simple data mapping: "$body/in2:invoke/idInformativa"(int) to "ObtenerRolesDeActividad"(int) -->
        <xsl:if test="$body/in2:invoke/idInformativa">
          <xsl:element name="ObtenerRolesDeActividad">
            <xsl:value-of select="$body/in2:invoke/idInformativa"/>
          </xsl:element>
        </xsl:if>
        <!-- a simple data mapping: "in3:Item"(int) to "EtapaId"(int) -->
        <xsl:for-each select="$body/in2:invoke/idEtapa/in3:Item">
          <!-- a simple data mapping: "."(int) to "EtapaId"(int) -->
          <xsl:if test=".">
            <EtapaId>
              <xsl:value-of select="."/>
            </EtapaId>
          </xsl:if>
        </xsl:for-each>
      </input_ObtenerRolesDeActividad>
    </out:ObtenerRolesDeActividad>
  </xsl:template>

  <!-- *****************    Utility Templates    ******************  -->
  <!-- copy the namespace declarations from the source to the target -->
  <xsl:template name="copyNamespaceDeclarations">
    <xsl:param name="root"/>
    <xsl:for-each select="$root/namespace::*[not(name() = '')]">
      <xsl:copy/>
    </xsl:for-each>
  </xsl:template>
</xsl:stylesheet>
