<?xml version="1.0" encoding="UTF-8"?>
<!-- @generated mapFile="ObtenerTeamInformativa/output_map_res_1.map" md5sum="36a0a6695c539581ba60d878fb72ea49" version="8.0.400" -->
<!--
*****************************************************************************
*   This file has been generated by the IBM XML Mapping Editor.
*
*   Mapping file:		output_map_res_1.map
*   Map declaration(s):	output_map_res_1
*   Input file(s):		smo://smo/name%3Dwsdl-primary/message%3D%257Bhttp%253A%252F%252FIBCRA_Mediaciones_Lib%252FObtenerActividadDesc%252FObtenerActividadDesc%257DObtenerTeamInformativaResponseMsg/xpath%3D%252Fbody/smo.xsd
*   Output file(s):		smo://smo/name%3Dwsdl-primary/message%3D%257Bhttp%253A%252F%252FIBCRAAI%252FAIS%252FAIS_ObtenerTeamInformativa%257DinvokeResponseMsg/xpath%3D%252Fbody/smo.xsd
*
*   Note: Do not modify the contents of this file as it is overwritten
*         each time the mapping model is updated.
*****************************************************************************
-->
<xsl:stylesheet
    xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
    xmlns:xalan="http://xml.apache.org/xslt"
    xmlns:math="http://exslt.org/math"
    xmlns:str="http://exslt.org/strings"
    xmlns:set="http://exslt.org/sets"
    xmlns:date="http://exslt.org/dates-and-times"
    xmlns:exsl="http://exslt.org/common"
    xmlns:xs4xs="http://www.w3.org/2001/XMLSchema"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:in2="http://IBCRA_Mediaciones_Lib/ObtenerComentarioSolicitud"
    xmlns:in4="http://IBCRA_Mediaciones_Lib/ObtenerSolicitudInformativa"
    xmlns:in3="http://IBCRA_Mediaciones_Lib/ObtenerInformativas"
    xmlns:io5="http://www.ibm.com/xmlns/prod/websphere/http/sca/6.1.0"
    xmlns:io4="http://www.w3.org/2003/05/soap-envelope"
    xmlns:io3="http://www.ibm.com/xmlns/prod/websphere/mq/sca/6.0.0"
    xmlns:io2="http://www.ibm.com/websphere/sibx/smo/v6.0.1"
    xmlns:in9="http://IBCRA_Mediaciones_Lib/ObtenerActividadDesc"
    xmlns:in10="http://IBCRA_Mediaciones_Lib/ObtenerHistoricoInformativa"
    xmlns:io6="http://www.w3.org/2005/08/addressing"
    xmlns:in5="http://IBCRA_Mediaciones_Lib/ObtenerTeamInformativa"
    xmlns:in6="http://IBCRA_Mediaciones_Lib/ObtenerDatosPortal"
    xmlns:in="http://IBCRA_Mediaciones_Lib/ObtenerActividadDesc/ObtenerActividadDesc"
    xmlns:in7="wsdl.http://IBCRA_Mediaciones_Lib/ObtenerActividadDesc/ObtenerActividadDesc"
    xmlns:io="http://schemas.xmlsoap.org/ws/2004/08/addressing"
    xmlns:in8="http://IBCRA_Mediaciones_Lib/ObtenerSolicitudEstadoIdCUP"
    xmlns:out3="http://IBCRAAI/AIS/AIS_ObtenerTeamInformativa"
    xmlns:out2="wsdl.http://IBCRAAI/AIS/AIS_ObtenerTeamInformativa"
    xmlns:out="http://IBCRABO"
    xmlns:in29="http://IBCRA_Mediaciones_Lib/ObtenerInformativasReintento"
    xmlns:in28="http://IBCRA_Mediaciones_Lib/ObtenerInformativaRectificativa"
    xmlns:in27="http://IBCRA_Mediaciones_Lib/ObtenerActividadesInformativa"
    xmlns:in26="http://IBCRA_Mediaciones_Lib/ConsultaInformativaGruposBPM"
    xmlns:in25="http://IBCRA_Mediaciones_Lib/ObtenerComboInformativas"
    xmlns:in24="http://IBCRA_Mediaciones_Lib/ObtenerFechaPorDiaHabilSemanalC"
    xmlns:in23="http://IBCRA_Mediaciones_Lib/ObtenerMaximoDiaHabilSemanalC"
    xmlns:in22="http://IBCRA_Mediaciones_Lib/ConsultaInformativaPorID"
    xmlns:in21="http://IBCRA_Mediaciones_Lib/ObtenerMaximoDiaHabilAnual"
    xmlns:in20="http://IBCRA_Mediaciones_Lib/ObtenerPeriodoFecha"
    xmlns:in19="http://IBCRA_Mediaciones_Lib/ObtenerFechaPorDiaHabilMes"
    xmlns:in36="http://IBCRA_Mediaciones_Lib/IniciarIntanciaInformativa_InsertarSolicitud"
    xmlns:in18="http://IBCRA_Mediaciones_Lib/ObtenerInformativasPlanificadasPorFecha"
    xmlns:in15="http://IBCRA_Mediaciones_Lib/ObtenerMaximoDiaHabilTrimestre"
    xmlns:in14="http://IBCRA_Mediaciones_Lib/ObtenerRolesDeInformativa"
    xmlns:in17="http://IBCRA_Mediaciones_Lib/ObtenerMaximoDiaHabilSemestre"
    xmlns:in16="http://IBCRA_Mediaciones_Lib/ObtenerInformativaDemanda"
    xmlns:in11="http://IBCRA_Mediaciones_Lib/ObtenerInformativasPlanificadas"
    xmlns:in13="http://IBCRA_Mediaciones_Lib/ObtenerRolesDeActividad"
    xmlns:in31="http://IBCRA_Mediaciones_Lib/ObtenerMaximoDiaHabilMes"
    xmlns:in12="http://IBCRA_Mediaciones_Lib/ObtenerFechaPorDiaHabilSemestre"
    xmlns:in30="http://IBCRA_Mediaciones_Lib/ObtenerFechaPorDiaHabilAnual"
    xmlns:in33="http://IBCRA_Mediaciones_Lib/ConsultaInformativaPorFechas"
    xmlns:in32="http://IBCRA_Mediaciones_Lib/ObtenerFechaPorDiaHabilTrimestre"
    xmlns:in35="http://IBCRA_Mediaciones_Lib/ConsultaInformativaRectificativas"
    xmlns:in34="http://IBCRA_Mediaciones_Lib/ObtenerSolicitudinformativaActividad"
    xmlns:map="http://IBCRA_AIS/ObtenerTeamInformativa/output_map_res_1"
    xmlns:msl="http://www.ibm.com/xmlmap"
    exclude-result-prefixes="math str set date exsl map xalan msl"
    version="1.0">
  <xsl:output method="xml" encoding="UTF-8" indent="no"/>

  <!-- root wrapper template  -->
  <xsl:template match="/">
    <xsl:choose>
      <xsl:when test="msl:datamap">
        <msl:datamap>
          <xsl:element name="dataObject">
            <xsl:attribute name="xsi:type">
              <xsl:value-of select="'out2:invokeResponseMsg'"/>
            </xsl:attribute>
            <xsl:call-template name="map:output_map_res_12">
              <xsl:with-param name="body" select="msl:datamap/dataObject[1]"/>
            </xsl:call-template>
          </xsl:element>
        </msl:datamap>
      </xsl:when>
      <xsl:otherwise>
        <xsl:apply-templates select="body" mode="map:output_map_res_1"/>
      </xsl:otherwise>
    </xsl:choose>
  </xsl:template>

  <!-- This rule represents an element mapping: "body" to "body".  -->
  <xsl:template match="body"  mode="map:output_map_res_1">
    <body>
      <xsl:attribute name="xsi:type">
        <xsl:value-of select="'out2:invokeResponseMsg'"/>
      </xsl:attribute>
      <out3:invokeResponse>
        <teamsInformativa>
          <!-- a for-each transform: "TeamInformativa"(TeamInformativa) to "out:TeamInformativa"(TeamInformativa) -->
          <xsl:apply-templates select="in:ObtenerTeamInformativaResponse/output_ObtenerTeamInformativa/TeamInformativa" mode="localTeamInformativaToTeamInformativa_306784395"/>
        </teamsInformativa>
      </out3:invokeResponse>
    </body>
  </xsl:template>

  <!-- This rule represents a type mapping: "body" to "body".  -->
  <xsl:template name="map:output_map_res_12">
    <xsl:param name="body"/>
    <out3:invokeResponse>
      <teamsInformativa>
        <!-- a for-each transform: "TeamInformativa"(TeamInformativa) to "out:TeamInformativa"(TeamInformativa) -->
        <xsl:apply-templates select="$body/in:ObtenerTeamInformativaResponse/output_ObtenerTeamInformativa/TeamInformativa" mode="localTeamInformativaToTeamInformativa_306784395"/>
      </teamsInformativa>
    </out3:invokeResponse>
  </xsl:template>

  <!-- This rule represents a for-each transform: "TeamInformativa" to "out:TeamInformativa".  -->
  <xsl:template match="TeamInformativa"  mode="localTeamInformativaToTeamInformativa_306784395">
    <out:TeamInformativa>
      <!-- a simple data mapping: "Actividad"(string) to "out:Actividad"(string) -->
      <xsl:if test="Actividad">
        <out:Actividad>
          <xsl:value-of select="Actividad"/>
        </out:Actividad>
      </xsl:if>
      <!-- a simple data mapping: "rolBPM"(string) to "out:rolBPM"(string) -->
      <xsl:if test="rolBPM">
        <out:rolBPM>
          <xsl:value-of select="rolBPM"/>
        </out:rolBPM>
      </xsl:if>
      <!-- a simple data mapping: "ActividadId"(string) to "out:ActividadId"(string) -->
      <xsl:if test="ActividadId">
        <out:ActividadId>
          <xsl:value-of select="ActividadId"/>
        </out:ActividadId>
      </xsl:if>
      <!-- a simple data mapping: "slaEtapa"(dateTime) to "out:slaEtapa"(dateTime) -->
      <xsl:if test="slaEtapa">
        <out:slaEtapa>
          <xsl:value-of select="slaEtapa"/>
        </out:slaEtapa>
      </xsl:if>
    </out:TeamInformativa>
  </xsl:template>

  <!-- *****************    Utility Templates    ******************  -->
  <!-- copy the namespace declarations from the source to the target -->
  <xsl:template name="copyNamespaceDeclarations">
    <xsl:param name="root"/>
    <xsl:for-each select="$root/namespace::*[not(name() = '')]">
      <xsl:copy/>
    </xsl:for-each>
  </xsl:template>
</xsl:stylesheet>
