<?xml version="1.0" encoding="UTF-8"?>
<!-- @generated mapFile="ObtenerDatosPortal/output_map_res_1.map" md5sum="0a3d1729c5b8b8fbf1a8a1128cbdfbac" version="8.0.400" -->
<!--
*****************************************************************************
*   This file has been generated by the IBM XML Mapping Editor.
*
*   Mapping file:		output_map_res_1.map
*   Map declaration(s):	output_map_res_1
*   Input file(s):		smo://smo/name%3Dwsdl-primary/message%3D%257Bhttp%253A%252F%252FIBCRA_Mediaciones_Lib%252FObtenerActividadDesc%252FObtenerActividadDesc%257DObtenerDatosPortalResponseMsg/xpath%3D%252Fbody/smo.xsd
*   Output file(s):		smo://smo/name%3Dwsdl-primary/message%3D%257Bhttp%253A%252F%252FIBCRAAI%252FAIS%252FAIS_ObtenerDatosPortal%257DinvokeResponseMsg/xpath%3D%252Fbody/smo.xsd
*
*   Note: Do not modify the contents of this file as it is overwritten
*         each time the mapping model is updated.
*****************************************************************************
-->
<xsl:stylesheet
    xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
    xmlns:xalan="http://xml.apache.org/xslt"
    xmlns:math="http://exslt.org/math"
    xmlns:str="http://exslt.org/strings"
    xmlns:set="http://exslt.org/sets"
    xmlns:date="http://exslt.org/dates-and-times"
    xmlns:exsl="http://exslt.org/common"
    xmlns:xs4xs="http://www.w3.org/2001/XMLSchema"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:in2="http://IBCRA_Mediaciones_Lib/ObtenerDatosPortal"
    xmlns:in4="http://IBCRA_Mediaciones_Lib/ObtenerActividadDesc"
    xmlns:in3="wsdl.http://IBCRA_Mediaciones_Lib/ObtenerActividadDesc/ObtenerActividadDesc"
    xmlns:io5="http://www.ibm.com/xmlns/prod/websphere/http/sca/6.1.0"
    xmlns:io4="http://www.w3.org/2003/05/soap-envelope"
    xmlns:io3="http://www.ibm.com/xmlns/prod/websphere/mq/sca/6.0.0"
    xmlns:io2="http://www.ibm.com/websphere/sibx/smo/v6.0.1"
    xmlns:io6="http://www.w3.org/2005/08/addressing"
    xmlns:in="http://IBCRA_Mediaciones_Lib/ObtenerActividadDesc/ObtenerActividadDesc"
    xmlns:io="http://schemas.xmlsoap.org/ws/2004/08/addressing"
    xmlns:out3="wsdl.http://IBCRAAI/AIS/AIS_ObtenerDatosPortal"
    xmlns:out2="http://IBCRAAI/AIS/AIS_ObtenerDatosPortal"
    xmlns:out="http://IBCRABO"
    xmlns:in29="http://IBCRA_Mediaciones_Lib/ObtenerMaximoDiaHabilMes"
    xmlns:in28="http://IBCRA_Mediaciones_Lib/ObtenerFechaPorDiaHabilAnual"
    xmlns:in27="http://IBCRA_Mediaciones_Lib/ObtenerInformativasReintento"
    xmlns:in26="http://IBCRA_Mediaciones_Lib/ObtenerInformativaRectificativa"
    xmlns:in25="http://IBCRA_Mediaciones_Lib/ObtenerActividadesInformativa"
    xmlns:in24="http://IBCRA_Mediaciones_Lib/ConsultaInformativaGruposBPM"
    xmlns:in23="http://IBCRA_Mediaciones_Lib/ObtenerComboInformativas"
    xmlns:in22="http://IBCRA_Mediaciones_Lib/ObtenerFechaPorDiaHabilSemanalC"
    xmlns:in21="http://IBCRA_Mediaciones_Lib/ObtenerMaximoDiaHabilSemanalC"
    xmlns:in20="http://IBCRA_Mediaciones_Lib/ConsultaInformativaPorID"
    xmlns:in19="http://IBCRA_Mediaciones_Lib/ObtenerMaximoDiaHabilAnual"
    xmlns:in36="http://IBCRA_Mediaciones_Lib/ObtenerHistoricoInformativa"
    xmlns:in18="http://IBCRA_Mediaciones_Lib/ObtenerPeriodoFecha"
    xmlns:in15="http://IBCRA_Mediaciones_Lib/ObtenerInformativasPlanificadasPorFecha"
    xmlns:in14="http://IBCRA_Mediaciones_Lib/ObtenerMaximoDiaHabilSemestre"
    xmlns:in17="http://IBCRA_Mediaciones_Lib/ObtenerTeamInformativa"
    xmlns:in16="http://IBCRA_Mediaciones_Lib/ObtenerFechaPorDiaHabilMes"
    xmlns:in11="http://IBCRA_Mediaciones_Lib/ObtenerMaximoDiaHabilTrimestre"
    xmlns:in9="http://IBCRA_Mediaciones_Lib/ObtenerInformativas"
    xmlns:in10="http://IBCRA_Mediaciones_Lib/ObtenerRolesDeInformativa"
    xmlns:in31="http://IBCRA_Mediaciones_Lib/ConsultaInformativaPorFechas"
    xmlns:in13="http://IBCRA_Mediaciones_Lib/ObtenerInformativaDemanda"
    xmlns:in30="http://IBCRA_Mediaciones_Lib/ObtenerFechaPorDiaHabilTrimestre"
    xmlns:in12="http://IBCRA_Mediaciones_Lib/ObtenerSolicitudInformativa"
    xmlns:in33="http://IBCRA_Mediaciones_Lib/ObtenerSolicitudinformativaActividad"
    xmlns:in5="http://IBCRA_Mediaciones_Lib/ObtenerInformativasPlanificadas"
    xmlns:in32="http://IBCRA_Mediaciones_Lib/ObtenerSolicitudEstadoIdCUP"
    xmlns:in6="http://IBCRA_Mediaciones_Lib/ObtenerComentarioSolicitud"
    xmlns:in35="http://IBCRA_Mediaciones_Lib/IniciarIntanciaInformativa_InsertarSolicitud"
    xmlns:in7="http://IBCRA_Mediaciones_Lib/ObtenerFechaPorDiaHabilSemestre"
    xmlns:in34="http://IBCRA_Mediaciones_Lib/ConsultaInformativaRectificativas"
    xmlns:in8="http://IBCRA_Mediaciones_Lib/ObtenerRolesDeActividad"
    xmlns:map="http://IBCRA_AIS/ObtenerDatosPortal/output_map_res_1"
    xmlns:msl="http://www.ibm.com/xmlmap"
    exclude-result-prefixes="math str set date exsl map xalan msl"
    version="1.0">
  <xsl:output method="xml" encoding="UTF-8" indent="no"/>

  <!-- root wrapper template  -->
  <xsl:template match="/">
    <xsl:choose>
      <xsl:when test="msl:datamap">
        <msl:datamap>
          <xsl:element name="dataObject">
            <xsl:attribute name="xsi:type">
              <xsl:value-of select="'out3:invokeResponseMsg'"/>
            </xsl:attribute>
            <xsl:call-template name="map:output_map_res_12">
              <xsl:with-param name="body" select="msl:datamap/dataObject[1]"/>
            </xsl:call-template>
          </xsl:element>
        </msl:datamap>
      </xsl:when>
      <xsl:otherwise>
        <xsl:apply-templates select="body" mode="map:output_map_res_1"/>
      </xsl:otherwise>
    </xsl:choose>
  </xsl:template>

  <!-- This rule represents an element mapping: "body" to "body".  -->
  <xsl:template match="body"  mode="map:output_map_res_1">
    <body>
      <xsl:attribute name="xsi:type">
        <xsl:value-of select="'out3:invokeResponseMsg'"/>
      </xsl:attribute>
      <out2:invokeResponse>
        <DatosPortal>
          <!-- a simple data mapping: "in:ObtenerDatosPortalResponse/output_ObtenerDatosPortal/nombreInformativa"(string) to "out:nombreInformativa"(string) -->
          <xsl:if test="in:ObtenerDatosPortalResponse/output_ObtenerDatosPortal/nombreInformativa">
            <xsl:element name="out:nombreInformativa">
              <xsl:value-of select="in:ObtenerDatosPortalResponse/output_ObtenerDatosPortal/nombreInformativa"/>
            </xsl:element>
          </xsl:if>
          <!-- a simple data mapping: "in:ObtenerDatosPortalResponse/output_ObtenerDatosPortal/fechaDePresentacion"(string) to "out:fechaDePresentacion"(string) -->
          <xsl:if test="in:ObtenerDatosPortalResponse/output_ObtenerDatosPortal/fechaDePresentacion">
            <xsl:element name="out:fechaDePresentacion">
              <xsl:value-of select="in:ObtenerDatosPortalResponse/output_ObtenerDatosPortal/fechaDePresentacion"/>
            </xsl:element>
          </xsl:if>
          <!-- a simple data mapping: "in:ObtenerDatosPortalResponse/output_ObtenerDatosPortal/tipoDeInformativa"(string) to "out:tipoDeInformativa"(string) -->
          <xsl:if test="in:ObtenerDatosPortalResponse/output_ObtenerDatosPortal/tipoDeInformativa">
            <xsl:element name="out:tipoDeInformativa">
              <xsl:value-of select="in:ObtenerDatosPortalResponse/output_ObtenerDatosPortal/tipoDeInformativa"/>
            </xsl:element>
          </xsl:if>
        </DatosPortal>
      </out2:invokeResponse>
    </body>
  </xsl:template>

  <!-- This rule represents a type mapping: "body" to "body".  -->
  <xsl:template name="map:output_map_res_12">
    <xsl:param name="body"/>
    <out2:invokeResponse>
      <DatosPortal>
        <!-- a simple data mapping: "$body/in:ObtenerDatosPortalResponse/output_ObtenerDatosPortal/nombreInformativa"(string) to "out:nombreInformativa"(string) -->
        <xsl:if test="$body/in:ObtenerDatosPortalResponse/output_ObtenerDatosPortal/nombreInformativa">
          <xsl:element name="out:nombreInformativa">
            <xsl:value-of select="$body/in:ObtenerDatosPortalResponse/output_ObtenerDatosPortal/nombreInformativa"/>
          </xsl:element>
        </xsl:if>
        <!-- a simple data mapping: "$body/in:ObtenerDatosPortalResponse/output_ObtenerDatosPortal/fechaDePresentacion"(string) to "out:fechaDePresentacion"(string) -->
        <xsl:if test="$body/in:ObtenerDatosPortalResponse/output_ObtenerDatosPortal/fechaDePresentacion">
          <xsl:element name="out:fechaDePresentacion">
            <xsl:value-of select="$body/in:ObtenerDatosPortalResponse/output_ObtenerDatosPortal/fechaDePresentacion"/>
          </xsl:element>
        </xsl:if>
        <!-- a simple data mapping: "$body/in:ObtenerDatosPortalResponse/output_ObtenerDatosPortal/tipoDeInformativa"(string) to "out:tipoDeInformativa"(string) -->
        <xsl:if test="$body/in:ObtenerDatosPortalResponse/output_ObtenerDatosPortal/tipoDeInformativa">
          <xsl:element name="out:tipoDeInformativa">
            <xsl:value-of select="$body/in:ObtenerDatosPortalResponse/output_ObtenerDatosPortal/tipoDeInformativa"/>
          </xsl:element>
        </xsl:if>
      </DatosPortal>
    </out2:invokeResponse>
  </xsl:template>

  <!-- *****************    Utility Templates    ******************  -->
  <!-- copy the namespace declarations from the source to the target -->
  <xsl:template name="copyNamespaceDeclarations">
    <xsl:param name="root"/>
    <xsl:for-each select="$root/namespace::*[not(name() = '')]">
      <xsl:copy/>
    </xsl:for-each>
  </xsl:template>
</xsl:stylesheet>
